title: Rebecca Cottrell
email: r.e.cottrell@gmail.com
baseurl: ""
url: "https://quietsignals.co.uk"
github_username: rivalee

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed

# Add this to show future posts
future: true

# Exclude from processing
exclude:
  - .DS_Store